name: Deploy 3D Hoodie Viewer

on:
  push:
    branches: ["main"]
  workflow_dispatch:  # Enable manual deployment button

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for proper LFS fetching

      # 2. Setup Node.js (for potential future builds)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Validate critical files exist
      - name: Validate files
        run: |
          if [ ! -f "index.html" ]; then
            echo "::error::index.html not found!"
            exit 1
          fi
          echo "All required files present"

      # 4. Upload artifact directly (no build needed for static HTML)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"
          # Only include necessary files to reduce size
          exclude: |
            .github/
            .gitattributes
            .gitignore
            README.md
            *.yml
            node_modules/
            package*.json

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
